# Generated by Django 6.0.7 on 2026-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255, verbose_name='Expressão')),
                ('result', models.CharField(max_length=255, verbose_name='Resultado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
